from __future__ import annotations

# Schema fixo da tabela de resultado — 83 colunas.
# Usado em ResultadoService.salvar_no_postgres(predefined_columns=...) para garantir
# que a tabela exista com o schema completo mesmo quando todos os ciclos retornam
# SEM_RETORNO (sem linhas HANA no DataFrame).
COMPLEMENTO_NOTAS_DDL: dict[str, str] = {
    # --- fila Postgres ---
    "ID":                          "BIGINT",
    "TIPO_PROCESSO":               "TEXT",
    "STATUS":                      "TEXT",
    "STATUS_COMPLEMENTO_FIXO":     "TEXT",
    "TIPO":                        "TEXT",
    "N_CONTRATO":                  "TEXT",
    "DOC_COMPRA":                  "TEXT",
    "NUMERO_COCKPIT_ORIGINAL":     "TEXT",
    "CENTRO":                      "TEXT",
    "SAFRA":                       "TEXT",
    "MATERIAL":                    "TEXT",
    "COD_PARCEIRO":                "TEXT",
    "DATA_HORA_ULTIMA_ATUALIZACAO":"TEXT",
    "NUMERO_COCKPIT":              "TEXT",
    "MSG_RPA":                     "TEXT",
    "VTIN_CHAVE_ACESSO":           "TEXT",
    "VTIN_DT_PROC":                "TEXT",
    "VTIN_HR_PROC":                "TEXT",
    # --- controle de execução ---
    "PROCESS_NAME":                "TEXT",
    "DATA_EXECUCAO":               "TIMESTAMP",
    "STATUS_EXECUCAO":             "TEXT",
    "TEMPO_EXECUCAO":              "NUMERIC(18,6)",
    "MENSAGEM_ERRO":               "TEXT",
    # --- HANA — ZMMT0022 ---
    "ZMMT_MANDT":                  "TEXT",
    "ZMMT_ID":                     "TEXT",
    "ZMMT_CONTRATO":               "TEXT",
    "ZMMT_DATA":                   "TEXT",
    "ZMMT_QTDE":                   "NUMERIC(18,6)",
    "ZMMT_VALOR":                  "NUMERIC(18,6)",
    "ZMMT_MIRO_DATA":              "TEXT",
    "ZMMT_MIRO_HORA":              "TEXT",
    "ZMMT_MIRO_DOC":               "TEXT",
    "ZMMT_MIRO_ANO":               "TEXT",
    "ZMMT_TIPO":                   "TEXT",
    # --- HANA — contrato/parceiro (comum a todos os processos) ---
    "CTR_MANDT":                   "TEXT",
    "BUKRS":                       "TEXT",
    "EBELN":                       "TEXT",
    "KONNR":                       "TEXT",
    "LIFNR":                       "TEXT",
    "NAME":                        "TEXT",
    "CPF_CNPJ":                    "TEXT",
    "IE":                          "TEXT",
    "NAME1_TEXT":                  "TEXT",
    # --- HANA — CTR exclusivo ARMAZEN (VBAK/VBAP) ---
    "TIPO_DOCUMENTO":              "TEXT",
    "CANAL_DISTRIBUICAO":          "TEXT",
    "DIVISAO":                     "TEXT",
    "ITEM_CONTRATO":               "TEXT",
    "CTR_MATERIAL":                "TEXT",
    "CTR_DESCRICAO_ITEM":          "TEXT",
    "CTR_QTD_PREVISTA":            "NUMERIC(18,6)",
    "CTR_UM":                      "TEXT",
    # --- HANA — VTIN / NF-e ---
    "PARCEIRO":                    "TEXT",
    "LOCAL":                       "TEXT",
    "DT_CRIACAO":                  "TEXT",
    "DOCNUM":                      "TEXT",
    "PESO_LIQUIDO":                "NUMERIC(18,6)",
    "VLR_NF":                      "NUMERIC(18,6)",
    "VTIN_STATUS":                 "TEXT",
    "VTIN_COD_STATUS_SEFAZ":       "TEXT",
    "VTIN_XML":                    "TEXT",
    "ITEM":                        "TEXT",
    "NCM":                         "TEXT",
    "CFOP":                        "TEXT",
    "VTIN_COD_PARCEIRO":           "TEXT",
    "VTIN_DT_CRIACAO":             "TEXT",
    "VTIN_HR_CRIACAO":             "TEXT",
    "VTIN_DT_EMISSAO":             "TEXT",
    "VTIN_CPF_CNPJ":               "TEXT",
    "VTIN_MODELO":                 "TEXT",
    "VTIN_EMPRESA":                "TEXT",
    "VTIN_CENTRO":                 "TEXT",
    "VTIN_NF_NUM":                 "TEXT",
    "VTIN_SERIE":                  "TEXT",
    "DIG_VER":                     "TEXT",
    "NUM_ALEATORIO":               "TEXT",
    "N_LOG":                       "TEXT",
    "VTIN_ANO":                    "TEXT",
    "VTIN_MES":                    "TEXT",
    "VTIN_QTDE":                   "NUMERIC(18,6)",
    "VTIN_VLR_NF":                 "NUMERIC(18,6)",
    "A_VTIN_VLR_NF":               "NUMERIC(18,6)",
    "RESULTADO":                   "NUMERIC(18,6)",
    "ORIGEM_MATCH":                "TEXT",
}
